const ContentBankData = [
  {
    title: "Company Policies",
    listItems: [
      "Leave Policy",
      "Loan Policy",
      "Domestic Travel Policy",
      "Domestic Travel Reimbursement",
      "International Travel Policy",
      "International Travel Reimbursement",
      "Petrol Reimbursement",
      "Car Policy",
      "Conveyance Policy",
      "Mobile Bill Reimbursement Policy",
      "Mobile Handset Policy",
      "Annual Health Checkup Policy",
      "Laptop Policy",
      "Driver Allowance Policy",
      "Working Hours and Attendance Policy",
      "Code of Conduct Policy",
      "IJB Policy",
      "Capex Policy",
      "Inventory Policy",
      "Credit Policy",
    ],
  },
  {
    title: "R&D Manuals",
    listItems: ["Apex Manual", "IMS R&D MANUAL 2024-25", "Procedure manual"],
  },
  {
    title: "HO - IT Policies",
    listItems: [
      "Acceptable Use Policy",
      "Access Managment policy",
      "Asset Managment Policy",
      "Change Managment policy",
      "Configuration Managment policy",
      "Cryptography policy",
      "Data Backup and Retention Policy",
      "Email Policy",
      "Environment, Health & Safety Policies Compendium",
      "Hardline policy",
      "Internet usage policy",
      "IT Incident Response Policy",
      "IT Security Risk Assessment Policy",
      "Log Managment policy",
      "Network and Teleworking & cloud service policy",
      "Password Managment policy",
      "Patch Managment policy",
      "Remote Access Policy",
    ],
  },
];

const ContentBankCompanyPolicyData = [
  { listItems: ["Leave Policy"] },
  { listItems: ["Loan Policy"] },
  { listItems: ["Domestic Travel Policy"] },
  { listItems: ["Domestic Travel Reimbursement"] },
  { listItems: ["International Travel Policy"] },
  { listItems: ["International Travel Reimbursement"] },
  { listItems: ["Petrol Reimbursement"] },
  { listItems: ["Car Policy"] },
  { listItems: ["Conveyance Policy"] },
  { listItems: ["Mobile Bill Reimbursement Policy"] },
  { listItems: ["Mobile Handset Policy"] },
  { listItems: ["Annual Health Checkup Policy"] },
  { listItems: ["Laptop Policy"] },
  { listItems: ["Driver Allowance Policy"] },
  { listItems: ["Working Hours and Attendance Policy"] },
  { listItems: ["Code of Conduct Policy"] },
  { listItems: ["IJB Policy"] },
  { listItems: ["Capex Policy"] },
  { listItems: ["Inventory Policy"] },
  { listItems: ["Credit Policy"] },
];

const ContentBankRnDData = [
  { listItems: ["Apex Manual"] },
  { listItems: ["IMS R&D MANUAL 2024-25"] },
  { listItems: ["Procedure manual"] },
];

const ContentBankHOITPolicyData = [
  { listItems: ["Acceptable Use Policy"] },
  { listItems: ["Access Management policy"] },
  { listItems: ["Asset Management Policy"] },
  { listItems: ["Change Management policy"] },
  { listItems: ["Configuration Management policy"] },
  { listItems: ["Cryptography policy"] },
  { listItems: ["Data Backup and Retention Policy"] },
  { listItems: ["Email Policy"] },
  { listItems: ["Environment, Health & Safety Policies Compendium"] },
  { listItems: ["Hardline policy"] },
  { listItems: ["Internet usage policy"] },
  { listItems: ["IT Incident Response Policy"] },
  { listItems: ["IT Security Risk Assessment Policy"] },
  { listItems: ["Log Management policy"] },
  { listItems: ["Network and Teleworking & cloud service policy"] },
  { listItems: ["Password Management policy"] },
  { listItems: ["Patch Management policy"] },
  { listItems: ["Remote Access Policy"] },
];

const ContentBankDataGeneral = [
  {
    title: "Company Policies",
    listItems: [
      "Leave Policy",
      "Loan Policy",
      "Domestic Travel Policy",
      "Domestic Travel Reimbursement",
      "International Travel Policy",
      "International Travel Reimbursement",
      "Petrol Reimbursement",
      "Car Policy",
      "Conveyance Policy",
      "Mobile Bill Reimbursement Policy",
      "Mobile Handset Policy",
      "Annual Health Checkup Policy",
      "Laptop Policy",
      "Driver Allowance Policy",
      "Working Hours and Attendance Policy",
      "Code of Conduct Policy",
      "IJB Policy",
      "Capex Policy",
      "Inventory Policy",
      "Credit Policy",
    ],
  },
  {
    title: "R&D Manuals",
    listItems: ["Apex Manual", "IMS R&D MANUAL 2024-25", "Procedure manual"],
  },
  {
    title: "HO - IT Policies",
    listItems: [
      "Acceptable Use Policy",
      "Access Managment policy",
      "Asset Managment Policy",
      "Change Managment policy",
      "Configuration Managment policy",
      "Cryptography policy",
      "Data Backup and Retention Policy",
      "Email Policy",
      "Environment, Health & Safety Policies Compendium",
      "Hardline policy",
      "Internet usage policy",
      "IT Incident Response Policy",
      "IT Security Risk Assessment Policy",
      "Log Managment policy",
      "Network and Teleworking & cloud service policy",
      "Password Managment policy",
      "Patch Managment policy",
      "Remote Access Policy",
    ],
  },
];

const ContentBankDataNew = [
  {
    title: "Procurement - Policies and Guidelines",
    listItems: [
      "Procurement Policy Manual",
      "Vendor Selection Guidelines",
      "Code of Conduct for Vendors & Contractors",
      "CapEx & OpEx Procurement Rules",
    ],
  },
  {
    title: "Procurement - Standard Operating Procedures (SOPs)",
    listItems: [
      "Purchase Requisition (PR) Process SOP",
      "Purchase Order (PO) Generation SOP",
      "Vendor Registration & Onboarding SOP",
      "Material Receipt & Inspection SOP",
      "Contract Management SOP",
      "Procurement for Services SOP (AMC, Consultancy, etc.)",
      "Emergency Procurement Procedure",
    ],
  },
  {
    title: "Procurement - Forms & Templates",
    listItems: [
      "Purchase Requisition Form",
      "Vendor Registration Form",
      "PO Amendment Request Form",
      "Non-Disclosure Agreement (NDA) Template",
      "Standard Purchase Order Format",
      "Asset/Inventory Indent Form",
      "Advance Payment Request Form",
      "CapEx Approval Form",
      "Bid Evaluation Template",
    ],
  },
  {
    title: "Procurement - Checklists & Reference Documents",
    listItems: [
      "Procurement Process Checklist",
      "Vendor Document Submission Checklist",
      "List of Approved Vendors",
      "Category-wise Procurement Contacts (key buyers per category)",
      "HSN/SAC Code Reference List",
      "Tax & Compliance Requirements for Procurement (PAN, GST, MSME, etc.)",
    ],
  },
];
